



arches:
- x86_64
stages:
- image: registry.access.redhat.com/ubi9/python-312:9.6-1755735361
  packages:
    - cuda-cudart-12-8
    - cuda-compat-12-8
    - cuda-nvcc-12-8
    - libibverbs-utils
    - infiniband-diags
    - libibumad3
    - librdmacm
    - librdmacm-utils
    - rdma-core
    - mlnx-tools